# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    type: parallel
    steps:
      test_lib:
        title: "Test Surround Library"
        type: "freestyle" # Run any command
        image: "python:3.6.10" # The image in which command will be executed
        working_directory: "${{clone}}"
        commands:
          # Go inside the surround library
          - cd surround

          # Install surround
          - python3 setup.py install

          # Run tests
          - python3 setup.py test

          # Run pylint tests
          - pip install pylint==2.4.3
          - pylint setup.py
          - find surround/ -iname "*.py" | xargs pylint
        stage: "test"

      test_cli:
        title: "Test Surround CLI"
        type: "freestyle" # Run any command
        image: "python:3.6.10" # The image in which command will be executed
        working_directory: "${{clone}}"
        commands:
          # Go inside the cli
          - cd surround_cli

          # Install surround
          - python3 setup.py install

          # Run tests
          - python3 setup.py test

          # Run pylint tests
          - pylint setup.py
          - find surround_cli/ -iname "*.py" | xargs pylint

          # Run examples
          - cd ..
          - find examples/ -iname "*.py" | xargs pylint
          - ls examples/ | xargs -n 1 -I '{}' python3 examples/'{}'/main.py
        stage: "test"
